### ISSUE TITLE
Rename page Blog to Change Logs

### ISSUE THREAD

**Issue by edgardmarx** [chemnet-io/General#13]
There is a need for a change log web page registering all the changes in the ontology or dataset.
This page should contain the changes between the different versions.
Ask @looooph to provide the changes, write the change log in text format, and upload it to the NuBBE file directory in dino server.
Later, create the page containing those change logs and upload it to the Change Logs page.

**Comment by DomUndAlf** [comment]
@looooph please send me the changes required so I can start working on this :)

**Comment by DomUndAlf** [comment]
done
