### ISSUE TITLE
Publicize the workshop on ESWC

### ISSUE THREAD

**Issue by looooph** [chemnet-io/General#5]
Get in contact with the HTWK publication area to make an article of DINOBBIO workshop on Linkedin and HTWK webpage.

**Comment by DomUndAlf** [comment]
Do you know who I need to contact to do this?

**Comment by DomUndAlf** [comment]
is it christian.zoellner@htwk-leipzig.de?

**Comment by edgardmarx** [comment]
I think is Katrin Haase (https://www.htwk-leipzig.de/scripte/apdetails.php?uid=1181), contact her.
If is not she, she will know who is.

**Comment by DomUndAlf** [comment]
I just contacted her. Will keep you updated

**Comment by DomUndAlf** [comment]
She says that an accorimg article has already been published and sent me this link.
https://www.htwk-leipzig.de/forschen/aktuelles/detailansicht/artikel/6190 

sent her the latest Blogpost as a reference, I'm guessing thats not the correct workshop?

**Comment by edgardmarx** [comment]
No it is not the correct workshop. 
What she is referring to as the workshop was the Brazilian research visit (Forschungspartner besuchen) in Leipzig.
The workshop I want to publish is the ESWC one, for research.

**Comment by edgardmarx** [comment]
Links: https://dinobbio.aksw.org/blog.html#YST0?lang=en
workshop-website: https://aksw.org/bike/

**Comment by DomUndAlf** [comment]
This is the message I received (translated from german)

----
Mrs. Haase has suggested putting up a post on the faculty homepage for this purpose (see below). I would be responsible for this. For this, you would need to provide me with a draft text or at least bullet points on the key points that should be included in the news, as well as at least one image. It would be great to include statements/quotes from the winners as well.
---

Please provide me with the contacts of the winners, so I can put the stuff together. I am just going to pick an image from the blog post and summarize the post for the bulletpoints she asked for.

**Comment by paulorvdc** [comment]
For the winners, two groups have members in our team so that's easy. But for Bhushan you can write him at bhushan.zope.phd2021@sitpune.edu.in to ask for permission.
Also add me paulo.carmo@htwk-leipzig.de and Edgard edgard.marx@htwk-leipzig.de in cc

**Comment by looooph** [comment]
This is probably finished(as the article got published)
