### ISSUE TITLE
Add the workshop proceedings and paper to publications entry

### ISSUE THREAD

**Issue by looooph** [chemnet-io/General#6]
This ticket consists in adding to the publication list in DINOBBIO project website the workshop papers:

-  BiKE Challenge: Result of ChemiScope by using ChatGPT by Matthias Jooß, Jonas Gwozdz and Pit Fröhlich (HTWK, Germany)

- Improving natural product automatic extraction with named entity recognition by Stefan Schmidt-Dichte and István J. Mócsy (HTWK, Germany)

- Preface of the First International Biochemical
Knowledge Extraction Challenge (BiKE)
Edgard Marx1, Marilia Valli2, Joao da Silva e Silva2, Sanju Tiwari3 and
Paulo do Carmo1 (https://ceur-ws.org/Vol-3447/BiKE_Preface.pdf)

**Comment by DomUndAlf** [comment]
- check out past posts, check structure etc 
- google scholar, search for papers by name for example, get bib text citation, put the ones that are in the publication tab

(thats just for myself)

**Comment by edgardmarx** [comment]
They have to be added here: https://dinobbio.aksw.org/publications.html?lang=en
Check with @looooph how to edit the dinobbio page.

**Comment by DomUndAlf** [comment]
I just pushed one entry to the publications page to the repo. Can somebody please check it and tell me if I did it right? Just to make sure I upload the other two corrently

**Comment by edgardmarx** [comment]
The papers are missing the conference, including the bibsonomy at the end.
Talk with @paulorvdc to add the appropriated conference.

**Comment by paulorvdc** [comment]
Oh, google scholar did not index the conference because it was in a workshop proceeding.
I'll make a new template by hand and then you can just change title and author names:
```
@inproceedings{bike2023<paper>,
  author={<author_anmes>},
  booktitle={Joint Proceedings of the Second International Workshop on Knowledge Graph Generation From Text and the First International BiKE Challenge co-located with 20th Extended Semantic Conference (ESWC 2023)}, 
  title={<title_name>}, 
  year={2023},
}
```
I think something like this is better

**Comment by paulorvdc** [comment]
you can also use this template for the preface that has no bib yet

**Comment by DomUndAlf** [comment]
I corrected everything and added the info to the top publication.
Thanks Paolo :)
