### ISSUE TITLE
Create the chemnet website

### ISSUE THREAD

**Issue by looooph** [chemnet-io/General#8]
This issue consists in creating the main website from Chemnet.

Reference for inspiration: 

- https://bostondynamics.com/
- https://research.google/
- https://research.facebook.com/
- https://www.cas.org/

**Comment by DomUndAlf** [comment]
I just created a repository for this: https://github.com/chemnet-io/webpage

Will be doing research and think of a concept next. 

Idea: create a Landing page as a placeholder until the structure of the page is more clear.

Edgard, can you give me a list of bulletpoints that I can publish there so people who look at the page can get an idea about what will be there in the future?

@edgardmarx

**Comment by DomUndAlf** [comment]
<img width="430" alt="image" src="https://github.com/chemnet-io/General/assets/122815547/c27cc29b-afb7-435a-a971-dfaf096df988">

This is a screenshot of the chemnet logo I made. Any changes? Is there something else needed, like the chemnet lettering? @edgardmarx

**Comment by DomUndAlf** [comment]
<img width="344" alt="image" src="https://github.com/chemnet-io/General/assets/122815547/823db907-27a6-4a49-9324-643d9ea6c28a">

**Comment by DomUndAlf** [comment]
<img width="336" alt="image" src="https://github.com/chemnet-io/General/assets/122815547/ae5143d0-525d-4ee7-ba96-941e879f32c9">

**Comment by DomUndAlf** [comment]
I made a few last tweaks, this is the final svg 
![finales Logo](https://github.com/chemnet-io/General/assets/122815547/2a238d95-dbde-455d-930f-6deb76d3fd7f)

**Comment by DomUndAlf** [comment]
the preliminary version of the webpage is visible here: https://github.com/chemnet-io/webpage
