### ISSUE TITLE
Add publications in aksw.org website

### ISSUE THREAD

**Issue by looooph** [chemnet-io/General#9]
This task consists in creating the page for bibliography in aksw website: https://aksw.org/Publications.html

You should pull all publications from AKSW from bibsonomy  (https://www.bibsonomy.org/user/aksw) website, generate a JSON and use it  to display the publications in the web-page.

you can use google research page as an example: https://research.google/pubs/

**Comment by DomUndAlf** [comment]
@jonasgwozdz I dont know how to do this, maybe you can help?

**Comment by edgardmarx** [comment]
This task is for @jonasgwozdz

**Comment by edgardmarx** [comment]
some reference: https://alshedivat.github.io/al-folio/publications/
